# Generated by Django 6.0.4 on 2026-05-07 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=20)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('cuit', models.CharField(max_length=20)),
                ('legajo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=50)),
                ('tipo_unidad', models.CharField(max_length=50)),
                ('chofer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transporte.chofer')),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Completado', 'Completado'), ('Pendiente', 'Pendiente')], max_length=20)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='transporte.camion')),
            ],
        ),
    ]
