# Generated by Django 6.0.4 on 2026-04-21 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camion',
            name='chofer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transporte.chofer'),
        ),
        migrations.AddField(
            model_name='chofer',
            name='cuit',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chofer',
            name='legajo',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chofer',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
